# Generated by Django 3.2.6 on 2021-08-27 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=255)),
                ('openPrice', models.FloatField()),
                ('highPrice', models.FloatField()),
                ('lowPrice', models.FloatField()),
                ('closePrice', models.FloatField()),
                ('volume', models.IntegerField()),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
