# Generated by Django 3.2.6 on 2021-08-27 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_alter_stock_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='closePrice',
            new_name='close',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='highPrice',
            new_name='high',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='lowPrice',
            new_name='low',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='openPrice',
            new_name='open',
        ),
    ]
